In [5]:
#### Convert coffea output into root TH2's to feed into TUnfold
import coffea
import pickle
import uproot
import awkward as ak
import matplotlib.pyplot as plt
import numpy as np
# import ROOT

In [7]:
%matplotlib inline
# fname = "coffeaOutput/dijetHists_QCDsim_pt200.0_eta2.4_NewHist.pkl"
fname = "coffeaOutput/trijetHists_QCDsim_pt200.0_eta2.4_bbloose.pkl"
# fname ="coffeaOutput/trijetHistsTest_JetHT_pt200.0_eta2.4_bbloose.pkl"
with open(fname, "rb") as f:
    result = pickle.load( f )
if "JetHT" in fname:
    rootfile = uproot.recreate('trijetHistsJetHT.root')
# integrate and sum over axes
if "QCD" in fname:
    rootfile = uproot.recreate('trijetHistsQCDsim.root')
    rootfile['ptgen_mgen_u'] = result['response_matrix_u'].project("ptgen", "mgen")
    rootfile['ptgen_mgen_g;1'] = result['response_matrix_g'].project("ptgen","mgen")
    rootfile['ptreco_ptgen_u'] = result['response_matrix_u'].project("ptreco", "ptgen")
    rootfile['ptreco_ptgen_g'] = result['response_matrix_g'].project("ptreco","ptgen")
    rootfile['misses_ptgen_mgen'] = result['misses'].project("ptgen", "mgen")
    rootfile['fakes_ptreco_mreco'] = result['fakes'].project("ptreco","mreco")
    response_matrix_u_values, ptreco_edges, mreco_edges, ptgen_edges, mgen_edges = result['response_matrix_u'].project("ptreco", "mreco", "ptgen", "mgen").to_numpy()
    response_matrix_g_values = result['response_matrix_g'].project("ptreco", "mreco", "ptgen", "mgen").values()
    print(response_matrix_g_values.shape)
    ptreco_centers = (ptreco_edges[:-1]+ptreco_edges[1:])/2
    print(ptreco_centers[np.newaxis])
    mreco_centers = (mreco_edges[:-1]+mreco_edges[1:])/2
    ptgen_centers = (ptgen_edges[:-1]+ptgen_edges[1:])/2
    mgen_centers = (mgen_edges[:-1]+mgen_edges[1:])/2
    print(np.shape(response_matrix_g_values))
    print(np.shape(response_matrix_g_values[np.newaxis]))
    rootfile['response'] = {'groomed':response_matrix_g_values[np.newaxis],
                       'ungroomed':response_matrix_u_values[np.newaxis]}
    rootfile['centers'] = {'ptreco':ptreco_centers[np.newaxis], 'mreco':mreco_centers[np.newaxis], 
                      'ptgen':ptgen_centers[np.newaxis], 'mgen':mgen_centers[np.newaxis]}
rootfile['jet_ptreco_mreco_u'] = result['jet_pt_mass_reco_u'][{'dataset':sum}]
rootfile['jet_ptreco_mreco_g'] = result['jet_pt_mass_reco_g'][{'dataset':sum}]
rootfile.close()

(10, 11, 10, 21)
[[ 240.  320.  405.  485.  575.  660.  720.  775. 1050. 7150.]]
(10, 11, 10, 21)
(1, 10, 11, 10, 21)


In [8]:
# fname = uproot.open('root://cmsxrootd.fnal.gov//store/mc/RunIISummer20UL18NanoAODv9/QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/280000/42B4DEA0-C0E7-A944-80DC-1D107A0F63FB.root')

In [9]:
# print(fname["Events"].keys("*HTXS*"))

In [10]:
hists = uproot.open('trijetHistsQCDsim.root')
print(hists.keys())
print(hists['response']['groomed'].array().to_numpy())
print(len(hists['centers']['mreco'].array().to_numpy()))

['ptgen_mgen_u;1', 'ptgen_mgen_g;1;1', 'ptreco_ptgen_u;1', 'ptreco_ptgen_g;1', 'misses_ptgen_mgen;1', 'fakes_ptreco_mreco;1', 'response;1', 'centers;1', 'jet_ptreco_mreco_u;1', 'jet_ptreco_mreco_g;1']
[[[[[13. 20. 15. ...  0.  0.  0.]
    [ 1.  0.  0. ...  0.  0.  0.]
    [ 0.  0.  0. ...  0.  0.  0.]
    ...
    [ 0.  0.  0. ...  0.  0.  0.]
    [ 0.  0.  0. ...  0.  0.  0.]
    [ 0.  0.  0. ...  0.  0.  0.]]

   [[ 5.  5.  5. ...  0.  0.  0.]
    [ 0.  0.  0. ...  0.  0.  0.]
    [ 0.  0.  0. ...  0.  0.  0.]
    ...
    [ 0.  0.  0. ...  0.  0.  0.]
    [ 0.  0.  0. ...  0.  0.  0.]
    [ 0.  0.  0. ...  0.  0.  0.]]

   [[ 0.  6.  5. ...  0.  0.  0.]
    [ 0.  1.  0. ...  0.  0.  0.]
    [ 0.  0.  0. ...  0.  0.  0.]
    ...
    [ 0.  0.  0. ...  0.  0.  0.]
    [ 0.  0.  0. ...  0.  0.  0.]
    [ 0.  0.  0. ...  0.  0.  0.]]

   ...

   [[ 0.  0.  0. ...  0.  0.  0.]
    [ 0.  0.  0. ...  0.  0.  0.]
    [ 0.  0.  0. ...  0.  0.  0.]
    ...
    [ 0.  0.  0. ...  0.  0.  0.]
    [