In [1]:
#### Convert coffea output into root TH2's to feed into TUnfold
import coffea
import pickle
import uproot
import awkward as ak
import matplotlib.pyplot as plt
import numpy as np
# import ROOT

In [10]:
%matplotlib inline
# fname = "coffeaOutput/dijetHists_QCDsim_pt200.0_eta2.4_NewHist.pkl"
fname = "coffeaOutput/dijetHistsTest_QCDsim_pt200.0_eta2.5.pkl"
# fname = "coffeaOutput/trijetHists_QCDsim_pt200.0_eta2.4_bbloose.pkl"
# fname ="coffeaOutput/trijetHistsTest_JetHT_pt200.0_eta2.4_bbloose.pkl"
with open(fname, "rb") as f:
    result = pickle.load( f )
if "trijet" in fname:
    if "JetHT" in  fname:
        rootfile = uproot.recreate('trijetHistsJetHT.root')
    # integrate and sum over axes
    if "QCD" in fname:
        rootfile = uproot.recreate('trijetHistsQCDsim_ALL.root')
elif "dijet" in fname:
    if "JetHT" in  fname:
        rootfile = uproot.recreate('dijetHistsJetHT.root')
    # integrate and sum over axes
    if "QCD" in fname:
        rootfile = uproot.recreate('dijetHistsQCDsim_ALL.root')
    rootfile['ptgen_mgen_u'] = result['response_matrix_u'].project("ptgen", "mgen")
    rootfile['ptgen_mgen_g;1'] = result['response_matrix_g'].project("ptgen","mgen")
    rootfile['ptreco_ptgen_u'] = result['response_matrix_u'].project("ptreco", "ptgen")
    rootfile['ptreco_ptgen_g'] = result['response_matrix_g'].project("ptreco","ptgen")
    rootfile['misses_ptgen_mgen'] = result['misses'].project("ptgen", "mgen")
    rootfile['fakes_ptreco_mreco'] = result['fakes'].project("ptreco","mreco")
    response_matrix_u_values, ptreco_edges, mreco_edges, ptgen_edges, mgen_edges = result['response_matrix_u'].project("ptreco", "mreco", "ptgen", "mgen").to_numpy()
    response_matrix_g_values = result['response_matrix_g'].project("ptreco", "mreco", "ptgen", "mgen").values()
    print(response_matrix_g_values.shape)
    ptreco_centers = (ptreco_edges[:-1]+ptreco_edges[1:])/2
    print(ptreco_centers[np.newaxis])
    mreco_centers = (mreco_edges[:-1]+mreco_edges[1:])/2
    ptgen_centers = (ptgen_edges[:-1]+ptgen_edges[1:])/2
    mgen_centers = (mgen_edges[:-1]+mgen_edges[1:])/2
    print(np.shape(response_matrix_g_values))
    print(np.shape(response_matrix_g_values[np.newaxis]))
    rootfile['response'] = {'groomed':response_matrix_g_values[np.newaxis],
                       'ungroomed':response_matrix_u_values[np.newaxis]}
    rootfile['centers'] = {'ptreco':ptreco_centers[np.newaxis], 'mreco':mreco_centers[np.newaxis], 
                      'ptgen':ptgen_centers[np.newaxis], 'mgen':mgen_centers[np.newaxis]}
rootfile['jet_ptreco_mreco_u'] = result['jet_pt_mass_reco_u'][{'dataset':sum}]
rootfile['jet_ptreco_mreco_g'] = result['jet_pt_mass_reco_g'][{'dataset':sum}]
rootfile.close()

(10, 24, 10, 12)
[[ 240.  320.  405.  485.  575.  660.  720.  775. 1050. 7150.]]
(10, 24, 10, 12)
(1, 10, 24, 10, 12)


In [4]:
# fname = uproot.open('root://cmsxrootd.fnal.gov//store/mc/RunIISummer20UL18NanoAODv9/QCD_Pt_1400to1800_TuneCP5_13TeV_pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/280000/42B4DEA0-C0E7-A944-80DC-1D107A0F63FB.root')

In [5]:
# print(fname["Events"].keys("*HTXS*"))

In [7]:
hists = uproot.open('trijetHistsQCDsim_ALL.root')
print(hists.keys())
print(hists['response']['groomed'].array().to_numpy())
print(len(hists['centers']['mreco'].array().to_numpy()))

['ptgen_mgen_u;1', 'ptgen_mgen_g;1;1', 'ptreco_ptgen_u;1', 'ptreco_ptgen_g;1', 'misses_ptgen_mgen;1', 'fakes_ptreco_mreco;1', 'response;1', 'centers;1', 'jet_ptreco_mreco_u;1', 'jet_ptreco_mreco_g;1']
[[[[[ 38.  56.  39. ...   4.   2.   0.]
    [  2.   6.   2. ...   0.   0.   0.]
    [  0.   0.   0. ...   0.   0.   0.]
    ...
    [  0.   0.   0. ...   0.   0.   0.]
    [  0.   0.   0. ...   0.   0.   0.]
    [  0.   0.   0. ...   0.   0.   0.]]

   [[ 12.  94.  39. ...   2.   2.   2.]
    [  1.   6.   3. ...   0.   0.   1.]
    [  0.   1.   0. ...   0.   0.   0.]
    ...
    [  0.   0.   0. ...   0.   0.   0.]
    [  0.   0.   0. ...   0.   0.   0.]
    [  0.   0.   0. ...   0.   0.   0.]]

   [[ 23. 935. 486. ...  32.   7.   9.]
    [  4.  42.  35. ...   4.   1.   2.]
    [  0.   1.   0. ...   0.   0.   0.]
    ...
    [  0.   0.   0. ...   0.   0.   0.]
    [  0.   0.   0. ...   0.   0.   0.]
    [  0.   0.   0. ...   0.   0.   0.]]

   ...

   [[  0.   0.   0. ...   0.   0.   0.]
 